import { useState } from 'react'
import styles from './TermsModal.module.css'

export default function TermsModal({ onAccept }) {
  const [checked, setChecked] = useState(false)

  return (
    <div className={styles.overlay} role="dialog" aria-modal="true" aria-labelledby="terms-title">
      <div className={styles.modal}>
        <h2 id="terms-title" className={styles.title}>Before you continue</h2>
        <p className={styles.intro}>
          Please read the following before using DevKnow.
        </p>

        <ol className={styles.list}>
          <li>
            <strong>Keep questions general.</strong> Do not enter confidential,
            proprietary, or sensitive project data in your questions. This is a
            public learning platform — treat it like a public forum.
          </li>
          <li>
            <strong>This platform is for learning, not outsourcing work.</strong> DevKnow
            is designed to help you understand concepts and techniques. It is not
            a tool for generating work you submit as entirely your own.
          </li>
          <li>
            <strong>AI answers are drafts.</strong> Responses are generated by AI
            and reviewed by senior developers. They can contain errors — apply
            your own judgement before acting on any advice.
          </li>
          <li>
            <strong>Use the platform responsibly.</strong> Do not attempt to
            misuse, abuse, or circumvent the platform's moderation controls.
          </li>
        </ol>

        <label className={styles.checkLabel}>
          <input
            type="checkbox"
            checked={checked}
            onChange={(e) => setChecked(e.target.checked)}
          />
          I have read and agree to these terms
        </label>

        <button
          className={styles.button}
          disabled={!checked}
          onClick={onAccept}
        >
          Continue to DevKnow
        </button>
      </div>
    </div>
  )
}
