# Generated by Django 6.0.4 on 2026-06-10 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovedSeniorEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Email address that will automatically receive the Senior Developer role on signup.', max_length=254, unique=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, help_text='Optional note (e.g. name or team) for admin reference.', max_length=255)),
            ],
            options={
                'verbose_name': 'Approved Senior Email',
                'verbose_name_plural': 'Approved Senior Emails',
                'ordering': ['email'],
            },
        ),
    ]
